<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="17149" started-at="2019-07-18T16:13:26Z" finished-at="2019-07-18T16:13:43Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="17149" started-at="2019-07-18T16:13:26Z" finished-at="2019-07-18T16:13:43Z">
      <class name="com.framework.testcases.LoginTest">
        <test-method status="PASS" signature="setUpSuits()[pri:0, instance:com.framework.testcases.LoginTest@14acaea5]" name="setUpSuits" is-config="true" duration-ms="382" started-at="2019-07-18T21:43:25Z" finished-at="2019-07-18T21:43:26Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUpSuits -->
        <test-method status="PASS" signature="setUp()[pri:0, instance:com.framework.testcases.LoginTest@14acaea5]" name="setUp" is-config="true" duration-ms="8863" started-at="2019-07-18T21:43:26Z" finished-at="2019-07-18T21:43:35Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="FAIL" signature="testLoginApp()[pri:0, instance:com.framework.testcases.LoginTest@14acaea5]" name="testLoginApp" duration-ms="7256" started-at="2019-07-18T21:43:35Z" finished-at="2019-07-18T21:43:42Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:93)
	at org.testng.Assert.failNotEquals(Assert.java:512)
	at org.testng.Assert.assertTrue(Assert.java:41)
	at org.testng.Assert.assertTrue(Assert.java:51)
	at com.framework.testcases.LoginTest.testLoginApp(LoginTest.java:25)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testLoginApp -->
        <test-method status="PASS" signature="tearDownMethod(org.testng.ITestResult)[pri:0, instance:com.framework.testcases.LoginTest@14acaea5]" name="tearDownMethod" is-config="true" duration-ms="424" started-at="2019-07-18T21:43:42Z" finished-at="2019-07-18T21:43:42Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=testLoginApp status=FAILURE method=LoginTest.testLoginApp()[pri:0, instance:com.framework.testcases.LoginTest@14acaea5] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDownMethod -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:com.framework.testcases.LoginTest@14acaea5]" name="tearDown" is-config="true" duration-ms="576" started-at="2019-07-18T21:43:42Z" finished-at="2019-07-18T21:43:43Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.framework.testcases.LoginTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
